## Naive Bayes Algorithm

Naive Bayes Algorithm is based on **Bayes' Theorem**. It is defined as:

$$
P(y \mid x_1, x_2, ..., x_n) = \frac{P(x_1, x_2, ..., x_n \mid y) \cdot P(y)}{P(x_1, x_2, ..., x_n)}
$$

Where:  
- \( y \) is the **class variable**  
- \( x_1, x_2, ..., x_n \) are the **features**

---

### Assumption: Feature Independence

The algorithm assumes that the features are **independent** of each other. So, the equation becomes:

$$
P(y \mid x_1, x_2, ..., x_n) = \frac{P(x_1 \mid y) \cdot P(x_2 \mid y) \cdot \ldots \cdot P(x_n \mid y) \cdot P(y)}{P(x_1, x_2, ..., x_n)}
$$

Since the **denominator is constant** for a given input, we can write:

$$
P(y \mid x_1, x_2, ..., x_n) \propto P(x_1 \mid y) \cdot P(x_2 \mid y) \cdot \ldots \cdot P(x_n \mid y) \cdot P(y)
$$

---

### Final Step:

The **class with the highest probability** is the **output** of the Naive Bayes algorithm.


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.naive_bayes import GaussianNB , MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

In [3]:
# Load the Iris dataset
iris = load_iris()
# Create feature and target arrays
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the Gaussian Naive Bayes classifier
gnb = GaussianNB()

# Fit the model on the training data
gnb.fit(X_train, y_train)
# Make predictions on the test data
y_pred = gnb.predict(X_test)
# Calculate accuracy
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
# Print classification report
print(f"Classification Report:\n{classification_report(y_test, y_pred)}")
# Print confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}")

Accuracy: 0.98
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

Confusion Matrix:
[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [4]:
# Create Multinomial Naive Bayes classifier
mnb = MultinomialNB()
# Fit the model on the training data
mnb.fit(X_train, y_train)
# Make predictions on the test data
y_pred_mnb = mnb.predict(X_test)
# Calculate accuracy
print(f"Accuracy of Multinomial Naive Bayes: {accuracy_score(y_test, y_pred_mnb):.2f}")
# Print classification report
print(f"Classification Report:\n{classification_report(y_test, y_pred_mnb)}")
# Print confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred_mnb)}")

Accuracy of Multinomial Naive Bayes: 0.96
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      0.92      0.92        13
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45

Confusion Matrix:
[[19  0  0]
 [ 0 12  1]
 [ 0  1 12]]
